/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Plesac;
import domen.Takmicenje;
import forme.modovi.ModDomenske;
import forme.modovi.ModGlavne;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleTakmicenje;
import modeli.ModelTabelePlesac;

/**
 *
 * @author Nada
 */
public class FrmGlavna extends javax.swing.JFrame {

    private ModGlavne mod;

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        setujMod(ModGlavne.PRAZNA);
        txtUlogovaniTrener.setText(Kontroler.getInstance().getUlogovan().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlPretraga = new javax.swing.JPanel();
        lblKriterijum1 = new javax.swing.JLabel();
        lblKriterijum2 = new javax.swing.JLabel();
        txtKriterijum1 = new javax.swing.JTextField();
        txtKriterijum2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRezultat = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        lblUlogovaniTrener = new javax.swing.JLabel();
        txtUlogovaniTrener = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUnos = new javax.swing.JMenu();
        miUnosPlesaca = new javax.swing.JMenuItem();
        miUnosTakmicenja = new javax.swing.JMenuItem();
        menuPretraga = new javax.swing.JMenu();
        miPretragaPlesaca = new javax.swing.JMenuItem();
        miPretragaTakmicenja = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKriterijum1.setText("Kriterijum 1:");

        lblKriterijum2.setText("Kriterijum 2:");

        txtKriterijum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKriterijum1KeyReleased(evt);
            }
        });

        txtKriterijum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKriterijum2ActionPerformed(evt);
            }
        });
        txtKriterijum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKriterijum2KeyReleased(evt);
            }
        });

        tblRezultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblRezultat);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPretragaLayout = new javax.swing.GroupLayout(pnlPretraga);
        pnlPretraga.setLayout(pnlPretragaLayout);
        pnlPretragaLayout.setHorizontalGroup(
            pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPretragaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPretragaLayout.createSequentialGroup()
                        .addGroup(pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKriterijum1)
                            .addComponent(lblKriterijum2))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKriterijum1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(txtKriterijum2)))
                    .addGroup(pnlPretragaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalji)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlPretragaLayout.setVerticalGroup(
            pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPretragaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKriterijum1)
                    .addComponent(txtKriterijum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKriterijum2)
                    .addComponent(txtKriterijum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPretragaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPretragaLayout.createSequentialGroup()
                        .addComponent(btnDetalji)
                        .addGap(46, 46, 46))))
        );

        lblUlogovaniTrener.setText("Ulogovani trener:");

        txtUlogovaniTrener.setEnabled(false);

        menuUnos.setText("Unos");

        miUnosPlesaca.setText("Unos plesaca");
        miUnosPlesaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosPlesacaActionPerformed(evt);
            }
        });
        menuUnos.add(miUnosPlesaca);

        miUnosTakmicenja.setText("Unos takmicenja");
        miUnosTakmicenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosTakmicenjaActionPerformed(evt);
            }
        });
        menuUnos.add(miUnosTakmicenja);

        jMenuBar1.add(menuUnos);

        menuPretraga.setText("Pretraga");

        miPretragaPlesaca.setText("Pretraga plesaca");
        miPretragaPlesaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaPlesacaActionPerformed(evt);
            }
        });
        menuPretraga.add(miPretragaPlesaca);

        miPretragaTakmicenja.setText("Pretraga takmicenja");
        miPretragaTakmicenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaTakmicenjaActionPerformed(evt);
            }
        });
        menuPretraga.add(miPretragaTakmicenja);

        jMenuBar1.add(menuPretraga);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblUlogovaniTrener)
                        .addGap(60, 60, 60)
                        .addComponent(txtUlogovaniTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUlogovaniTrener)
                    .addComponent(txtUlogovaniTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(pnlPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUnosPlesacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosPlesacaActionPerformed
        new FrmPlesac(this, true, new Plesac(), ModDomenske.UNOS).setVisible(true);
    }//GEN-LAST:event_miUnosPlesacaActionPerformed

    private void txtKriterijum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKriterijum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKriterijum2ActionPerformed

    private void miUnosTakmicenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosTakmicenjaActionPerformed
        new FrmTakmicenje(this, true, new Takmicenje(), ModDomenske.UNOS).setVisible(true);
    }//GEN-LAST:event_miUnosTakmicenjaActionPerformed

    private void miPretragaPlesacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaPlesacaActionPerformed
        setujMod(ModGlavne.PRETRAGA_PLESACA);
        pretraga();
    }//GEN-LAST:event_miPretragaPlesacaActionPerformed

    private void miPretragaTakmicenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaTakmicenjaActionPerformed
        setujMod(ModGlavne.PRETRAGA_TAKMICENJA);
        pretraga();
    }//GEN-LAST:event_miPretragaTakmicenjaActionPerformed

    private void txtKriterijum1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKriterijum1KeyReleased
        pretraga();
    }//GEN-LAST:event_txtKriterijum1KeyReleased

    private void txtKriterijum2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKriterijum2KeyReleased
        pretraga();
    }//GEN-LAST:event_txtKriterijum2KeyReleased

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int i = tblRezultat.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite red iz tabele");;
            return;
        }
        if (mod == ModGlavne.PRETRAGA_PLESACA) {
            Plesac plesac = ((ModelTabelePlesac) tblRezultat.getModel()).getRed(i);
            new FrmPlesac(this, true, plesac, ModDomenske.PRIKAZ).setVisible(true);
        }
        if (mod == ModGlavne.PRETRAGA_TAKMICENJA) {
            Takmicenje takmicenje = ((ModelTabeleTakmicenje) tblRezultat.getModel()).getRed(i);
            new FrmTakmicenje(this, true, takmicenje, ModDomenske.PRIKAZ).setVisible(true);
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblKriterijum1;
    private javax.swing.JLabel lblKriterijum2;
    private javax.swing.JLabel lblUlogovaniTrener;
    private javax.swing.JMenu menuPretraga;
    private javax.swing.JMenu menuUnos;
    private javax.swing.JMenuItem miPretragaPlesaca;
    private javax.swing.JMenuItem miPretragaTakmicenja;
    private javax.swing.JMenuItem miUnosPlesaca;
    private javax.swing.JMenuItem miUnosTakmicenja;
    private javax.swing.JPanel pnlPretraga;
    private javax.swing.JTable tblRezultat;
    private javax.swing.JTextField txtKriterijum1;
    private javax.swing.JTextField txtKriterijum2;
    private javax.swing.JTextField txtUlogovaniTrener;
    // End of variables declaration//GEN-END:variables

    private void setujMod(ModGlavne mod) {
        this.mod = mod;
        switch (mod) {
            case PRAZNA:
                pnlPretraga.setVisible(false);
                break;
            case PRETRAGA_PLESACA:
                tblRezultat.setModel(new ModelTabelePlesac(new ArrayList<>()));
                lblKriterijum1.setText("ime i prezime: ");
                lblKriterijum2.setText("broj godina: ");
                pnlPretraga.setVisible(true);
                break;
            case PRETRAGA_TAKMICENJA:
                tblRezultat.setModel(new ModelTabeleTakmicenje(new ArrayList<>()));
                lblKriterijum1.setText("mesto: ");
                lblKriterijum2.setText("termin: ");
                pnlPretraga.setVisible(true);
                break;
        }
    }

    public void pretraga() {
        if (mod == ModGlavne.PRETRAGA_PLESACA) {
            pretragaPlesaca();
        }
        if (mod == ModGlavne.PRETRAGA_TAKMICENJA) {
            pretragaTakmicenja();
        }
    }

    private void pretragaPlesaca() {
        try{
            Plesac plesac = new Plesac();
            plesac.setIme(txtKriterijum1.getText());
            plesac.setPrezime(txtKriterijum1.getText());
            plesac.setBrojGodina(-1);
            try{
                plesac.setBrojGodina(Integer.parseInt(txtKriterijum2.getText()));
            }catch(Exception ex){
            }
            List<Plesac> lista = Kontroler.getInstance().pretragaPlesaca(plesac);
            ((ModelTabelePlesac)tblRezultat.getModel()).setLista(lista);
        }catch(Exception ex){            
            //Logger.getLogger(FrmGlavna.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void pretragaTakmicenja() {
        try {
            Takmicenje takmicenje = new Takmicenje();
            takmicenje.setMesto(txtKriterijum1.getText());
            try {
                takmicenje.setTermin(Kontroler.getInstance().parseDatum(txtKriterijum2.getText()));
            } catch (Exception ex) {
            }
            List<Takmicenje> lista = Kontroler.getInstance().pretragaTakmicenja(takmicenje);
            ((ModelTabeleTakmicenje)tblRezultat.getModel()).setLista(lista);
        } catch (Exception ex) {            
            //Logger.getLogger(FrmGlavna.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}

